-- Türkiye Tekdüzen Hesap Planı (TMS uyumlu)
-- Sınıf 1: Dönen Varlıklar
INSERT INTO ys_accounts (kod,ad,tip,sinif,ana_kod,normal_bakiye) VALUES
('1','DÖNEN VARLIKLAR','aktif','1',NULL,'borc'),
('10','HAZIR DEĞERLER','aktif','1','1','borc'),
('100','KASA','aktif','1','10','borc'),
('101','ALINAN ÇEKLER','aktif','1','10','borc'),
('102','BANKALAR','aktif','1','10','borc'),
('103','VERİLEN ÇEKLER VE ÖDEME EMİRLERİ','aktif','1','10','alacak'),
('108','DİĞER HAZIR DEĞERLER','aktif','1','10','borc'),
('11','MENKUL KIYMETLER','aktif','1','1','borc'),
('12','TİCARİ ALACAKLAR','aktif','1','1','borc'),
('120','ALICILAR','aktif','1','12','borc'),
('121','ALACAK SENETLERİ','aktif','1','12','borc'),
('126','VERİLEN DEPOZİTO VE TEMİNATLAR','aktif','1','12','borc'),
('128','ŞÜPHELİ TİCARİ ALACAKLAR','aktif','1','12','borc'),
('129','ŞÜPHELİ TİCARİ ALACAKLAR KARŞILIĞI','aktif','1','12','alacak'),
('13','DİĞER ALACAKLAR','aktif','1','1','borc'),
('131','ORTAKLARDAN ALACAKLAR','aktif','1','13','borc'),
('135','PERSONELDEN ALACAKLAR','aktif','1','13','borc'),
('136','DİĞER ÇEŞİTLİ ALACAKLAR','aktif','1','13','borc'),
('15','STOKLAR','aktif','1','1','borc'),
('150','İLK MADDE VE MALZEME','aktif','1','15','borc'),
('151','YARI MAMULLER','aktif','1','15','borc'),
('152','MAMULLER','aktif','1','15','borc'),
('153','TİCARİ MALLAR','aktif','1','15','borc'),
('157','DİĞER STOKLAR','aktif','1','15','borc'),
('158','STOK DEĞER DÜŞÜKLÜĞÜ KARŞILIĞI','aktif','1','15','alacak'),
('18','GELECEK AYLARA AİT GİDERLER','aktif','1','1','borc'),
('19','DİĞER DÖNEN VARLIKLAR','aktif','1','1','borc'),
('190','DEVREDEN KDV','aktif','1','19','borc'),
('191','İNDİRİLECEK KDV','aktif','1','19','borc'),
('195','İŞ AVANSLAR','aktif','1','19','borc'),
-- Sınıf 2: Duran Varlıklar
('2','DURAN VARLIKLAR','aktif','2',NULL,'borc'),
('22','TİCARİ ALACAKLAR','aktif','2','2','borc'),
('25','MADDİ DURAN VARLIKLAR','aktif','2','2','borc'),
('250','ARAZİ VE ARSALAR','aktif','2','25','borc'),
('251','YER ALTI VE YER ÜSTÜ DÜZENLEMELERİ','aktif','2','25','borc'),
('252','BİNALAR','aktif','2','25','borc'),
('253','TESİS MAKİNE VE CİHAZLAR','aktif','2','25','borc'),
('254','TAŞITLAR','aktif','2','25','borc'),
('255','DEMİRBAŞLAR','aktif','2','25','borc'),
('257','BİRİKMİŞ AMORTİSMANLAR','aktif','2','25','alacak'),
('26','MADDİ OLMAYAN DURAN VARLIKLAR','aktif','2','2','borc'),
('260','HAKLAR','aktif','2','26','borc'),
('268','BİRİKMİŞ İTFALAR','aktif','2','26','alacak'),
-- Sınıf 3: Kısa Vadeli Yabancı Kaynaklar
('3','KISA VADELİ YABANCI KAYNAKLAR','pasif','3',NULL,'alacak'),
('30','MALİ BORÇLAR','pasif','3','3','alacak'),
('300','BANKA KREDİLERİ','pasif','3','30','alacak'),
('303','UZUN VADELİ KREDİLERİN ANAPARA TAKSİTLERİ','pasif','3','30','alacak'),
('32','TİCARİ BORÇLAR','pasif','3','3','alacak'),
('320','SATICILAR','pasif','3','32','alacak'),
('321','BORÇ SENETLERİ','pasif','3','32','alacak'),
('326','ALINAN DEPOZİTO VE TEMİNATLAR','pasif','3','32','alacak'),
('33','DİĞER BORÇLAR','pasif','3','3','alacak'),
('331','ORTAKLARA BORÇLAR','pasif','3','33','alacak'),
('335','PERSONELE BORÇLAR','pasif','3','33','alacak'),
('336','DİĞER ÇEŞİTLİ BORÇLAR','pasif','3','33','alacak'),
('34','ALINAN AVANSLAR','pasif','3','3','alacak'),
('36','ÖDENECEK VERGİ VE YÜKÜMLÜLÜKLER','pasif','3','3','alacak'),
('360','ÖDENECEK VERGİ VE FONLAR','pasif','3','36','alacak'),
('361','ÖDENECEK SOSYAL GÜVENLİK KESİNTİLERİ','pasif','3','36','alacak'),
('368','VADESİ GEÇMİŞ ERTELENMİŞ VEYA TAKSİTLENDİRİLMİŞ VERGİ','pasif','3','36','alacak'),
('37','BORÇ VE GİDER KARŞILIKLARI','pasif','3','3','alacak'),
('370','DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI','pasif','3','37','alacak'),
('371','DÖNEM KARININ PEŞİN ÖDENEN VERGİ VE DİĞER YÜKÜMLÜLÜKLERİ','pasif','3','37','borc'),
('39','DİĞER KISA VADELİ YABANCI KAYNAKLAR','pasif','3','3','alacak'),
('391','HESAPLANAN KDV','pasif','3','39','alacak'),
-- Sınıf 4: Uzun Vadeli Yabancı Kaynaklar
('4','UZUN VADELİ YABANCI KAYNAKLAR','pasif','4',NULL,'alacak'),
('40','MALİ BORÇLAR','pasif','4','4','alacak'),
('400','BANKA KREDİLERİ','pasif','4','40','alacak'),
('42','TİCARİ BORÇLAR','pasif','4','4','alacak'),
('43','DİĞER BORÇLAR','pasif','4','4','alacak'),
('47','BORÇ VE GİDER KARŞILIKLARI','pasif','4','4','alacak'),
('472','KIDEM TAZMİNATI KARŞILIĞI','pasif','4','47','alacak'),
-- Sınıf 5: Özkaynaklar
('5','ÖZKAYNAKLAR','ozkaynaklar','5',NULL,'alacak'),
('50','ÖDENMİŞ SERMAYE','ozkaynaklar','5','5','alacak'),
('500','SERMAYE','ozkaynaklar','5','50','alacak'),
('52','SERMAYE YEDEKLERİ','ozkaynaklar','5','5','alacak'),
('54','KAR YEDEKLERİ','ozkaynaklar','5','5','alacak'),
('57','GEÇMİŞ YIL KARLARI','ozkaynaklar','5','5','alacak'),
('58','GEÇMİŞ YIL ZARARLARI','ozkaynaklar','5','5','borc'),
('59','DÖNEM NET KARI (ZARARI)','ozkaynaklar','5','5','alacak'),
('590','DÖNEM NET KARI','ozkaynaklar','5','59','alacak'),
('591','DÖNEM NET ZARARI','ozkaynaklar','5','59','borc'),
-- Sınıf 6: Gelir Tablosu
('6','GELİR TABLOSU HESAPLARI','gelir','6',NULL,'alacak'),
('60','BRÜT SATIŞLAR','gelir','6','6','alacak'),
('600','YURTİÇİ SATIŞLAR','gelir','6','60','alacak'),
('601','YURTDIŞI SATIŞLAR','gelir','6','60','alacak'),
('602','DİĞER GELİRLER','gelir','6','60','alacak'),
('61','SATIŞ İNDİRİMLERİ','gider','6','6','borc'),
('610','SATIŞTAN İADELER','gider','6','61','borc'),
('611','SATIŞ İSKONTOLARI','gider','6','61','borc'),
('62','SATIŞLARIN MALİYETİ','maliyet','6','6','borc'),
('620','SATILAN MAMULLER MALİYETİ','maliyet','6','62','borc'),
('621','SATILAN TİCARİ MALLAR MALİYETİ','maliyet','6','62','borc'),
('622','SATILAN HİZMET MALİYETİ','maliyet','6','62','borc'),
('63','FAALİYET GİDERLERİ','gider','6','6','borc'),
('630','ARAŞTIRMA VE GELİŞTİRME GİDERLERİ','gider','6','63','borc'),
('631','PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ','gider','6','63','borc'),
('632','GENEL YÖNETİM GİDERLERİ','gider','6','63','borc'),
('64','DİĞER FAALİYETLERDEN OLAĞAN GELİR VE KARLAR','gelir','6','6','alacak'),
('640','İŞTİRAKLERDEN TEMETTÜ GELİRLERİ','gelir','6','64','alacak'),
('641','BAĞLI ORTAKLIKLARDAN TEMETTÜ GELİRLERİ','gelir','6','64','alacak'),
('642','FAİZ GELİRLERİ','gelir','6','64','alacak'),
('644','KONUSU KALMAYAN KARŞILIKLAR','gelir','6','64','alacak'),
('645','MENKUL KIYMET SATIŞ KARLARI','gelir','6','64','alacak'),
('646','KAMBİYO KARLARI','gelir','6','64','alacak'),
('647','REESKONT FAİZ GELİRLERİ','gelir','6','64','alacak'),
('649','DİĞER OLAĞAN GELİR VE KARLAR','gelir','6','64','alacak'),
('65','DİĞER FAALİYETLERDEN OLAĞAN GİDER VE ZARARLAR','gider','6','6','borc'),
('653','KOMİSYON GİDERLERİ','gider','6','65','borc'),
('654','KARŞILIK GİDERLERİ','gider','6','65','borc'),
('655','MENKUL KIYMET SATIŞ ZARARLARI','gider','6','65','borc'),
('656','KAMBİYO ZARARLARI','gider','6','65','borc'),
('657','REESKONT FAİZ GİDERLERİ','gider','6','65','borc'),
('659','DİĞER OLAĞAN GİDER VE ZARARLAR','gider','6','65','borc'),
('67','OLAĞANDIŞI GELİR VE KARLAR','gelir','6','6','alacak'),
('679','DİĞER OLAĞANDIŞI GELİR VE KARLAR','gelir','6','67','alacak'),
('68','OLAĞANDIŞI GİDER VE ZARARLAR','gider','6','6','borc'),
('689','DİĞER OLAĞANDIŞI GİDER VE ZARARLAR','gider','6','68','borc'),
('69','DÖNEM NET KARI VEYA ZARARI','gelir','6','6','alacak'),
('690','DÖNEM KARI VEYA ZARARI','gelir','6','69','alacak'),
('691','DÖNEM KARI VERGİ VE DİĞER YASAL YÜKÜMLÜLÜK KARŞILIKLARI','gider','6','69','borc'),
('692','DÖNEM NET KARI VEYA ZARARI','gelir','6','69','alacak'),
-- Sınıf 7: Maliyet Hesapları
('7','MALİYET HESAPLARI','maliyet','7',NULL,'borc'),
('70','MALİYET MUHASEBE BAĞLANTI HESABI','maliyet','7','7','borc'),
('71','DİREKT İLK MADDE VE MALZEME GİDERLERİ','maliyet','7','7','borc'),
('72','DİREKT İŞÇİLİK GİDERLERİ','maliyet','7','7','borc'),
('73','GENEL ÜRETİM GİDERLERİ','maliyet','7','7','borc'),
('74','HİZMET ÜRETİM MALİYETİ','maliyet','7','7','borc'),
('75','ARAŞTIRMA VE GELİŞTİRME GİDERLERİ','maliyet','7','7','borc'),
('76','PAZARLAMA SATIŞ VE DAĞITIM GİDERLERİ','maliyet','7','7','borc'),
('77','GENEL YÖNETİM GİDERLERİ','maliyet','7','7','borc'),
('78','FİNANSMAN GİDERLERİ','maliyet','7','7','borc'),
('780','FİNANSMAN GİDERLERİ','maliyet','7','78','borc');
